### ISSUE TITLE
BNGBlaster counts rx-packets when disabling qdisc-bypass

### ISSUE THREAD

**Issue by SoerenBusse** [rtbrick/bngblaster#206]
**Describe the bug**

When configuring `qdisc-bypass: false` and a downstream-only stream, BNG-Blaster shows rx-packets on the network-interface, although no rx-packets are received:
![image](https://github.com/rtbrick/bngblaster/assets/7796567/34317630-9fb6-4996-9293-aca085e082b3)

This wrongly counted rx-packets are included in the report, too:
```
Interface: veth1.1
------------------------------------------------------------------------------
  TX:                     66034 packets         18876671 bytes
  TX Polled:                  0
  RX:                     66086 packets         18881052 bytes
  RX Protocol Error:          0 packets
  RX Unknown:                 0 packets
  RX Polled:                945

A10NSP Interface: veth1.1
  TX:                     66034 packets         18549487 bytes
  RX:                     66086 packets         18881052 bytes
  TX Stream:              66021 packets
  RX Stream:                 33 packets                0 loss
  Session-Traffic:
    TX IPv4:                 33 packets
    RX IPv4:                 33 packets                0 loss
    TX IPv6:                  0 packets
    RX IPv6:                  0 packets                0 loss
    TX IPv6PD:                0 packets
    RX IPv6PD:                0 packets                0 loss

Interface: veth1.2
------------------------------------------------------------------------------
  TX:                        54 packets             4655 bytes
  TX Polled:                  0
  RX:                     66087 packets         18617162 bytes
  RX Protocol Error:          0 packets
  RX Unknown:                 0 packets
  RX Polled:                945

Access Interface: veth1.2
  TX:                        54 packets             4655 bytes
  RX:                     66087 packets         18617162 bytes
  RX Multicast:               0 packets                0 loss
  TX Stream:                 33 packets
  RX Stream:              66021 packets                0 loss
  Session-Traffic:
    TX IPv4:                 33 packets
    RX IPv4:                 33 packets                0 loss
    TX IPv6:                  0 packets
    RX IPv6:                  0 packets                0 loss
    TX IPv6PD:                0 packets
    RX IPv6PD:                0 packets                0 loss
```

When setting `qdisc-bypass: true` the rx-packets are not counted:
![image](https://github.com/rtbrick/bngblaster/assets/7796567/8d053870-1886-46d1-b6d2-43a53bd487ab)

**To Reproduce**
Use the PPPoE Quick-Start guide and disable qdisc-bypass.

Version (`bngblaster -v`):

```
Version: DEV
Compiler: GNU (11.4.0)
GIT:
  REF: HEAD (0.8.23)
  SHA: 2aba470164a8b779579f10c329e7a9790cb9f454
IO Modes: packet_mmap_raw (default), packet_mmap, raw, dpdk
```

JSON configuration:
```json
{
    "interfaces": {
        "qdisc-bypass": false,
        "a10nsp": [
            {
                "__comment__": "PPPoE Server",
                "interface": "veth1.1"
            }
        ],
        "access": [
            {
                "__comment__": "PPPoE Client",
                "interface": "veth1.2",
                "type": "pppoe",
                "outer-vlan-min": 1,
                "outer-vlan-max": 4000,
                "inner-vlan": 7,
                "stream-group-id": 1
            }
        ]
    },
    "pppoe": {
        "reconnect": true
    },
    "dhcpv6": {
        "enable": false
    },
    "session-traffic": {
        "ipv4-pps": 1
    },
    "streams": [
        {
            "stream-group-id": 1,
            "name": "S1",
            "type": "ipv4",
            "direction": "downstream",
            "priority": 128,
            "length": 256,
            "pps": 2000,
            "a10nsp-interface": "veth1.1"
        }
    ]
}
```

1. Configure `qdisc-bypass: false`
2. Run BNG Blaster and observe rx-packets

**Additional context**

We want to bypass qdisc in egress to apply `tc netem` rules for simulating network issues like packet loss, latency etc.

**Comment by SoerenBusse** [comment]
Hi @GIC-de, the issue still exists on 0.9.7. Do you have any idea, what is the reason for it?

**Comment by jackpbreilly** [comment]
Looks like when we set "qdisc-bypass: true" we call from bbl_rx_stream_access and when we set "qdisc-bypass: false" we call from bbl_rx_stream_a10nsp. So I guess from this we are just rx what we are tx...looking some more.

qdisc-bypass: true
```
Breakpoint 1, bbl_stream_rx (eth=0x555555b807a0, mac=0x0)
    at /home/jack/bngblaster/code/bngblaster/src/bbl_stream.c:2248
warning: Source file is more recent than executable.
2248	    bbl_bbl_s *bbl = eth->bbl;
(gdb) bt
#0  bbl_stream_rx (eth=0x555555b807a0, mac=0x0)
    at /home/jack/bngblaster/code/bngblaster/src/bbl_stream.c:2248
#1  0x00005555555bb903 in bbl_rx_stream_access (interface=0x555555b98c30, eth=0x555555b807a0)
    at /home/jack/bngblaster/code/bngblaster/src/bbl_rx.c:39
#2  0x00005555555bbb57 in bbl_rx_handler (interface=0x555555b8e780, eth=0x555555b807a0)
    at /home/jack/bngblaster/code/bngblaster/src/bbl_rx.c:114
#3  0x00005555555e9688 in io_packet_mmap_rx_job (timer=0x555555b83270)
    at /home/jack/bngblaster/code/bngblaster/src/io/io_packet_mmap.c:100
#4  0x000055555555e017 in timer_walk (root=0x555555b802a0)
    at /home/jack/bngblaster/code/common/src/timer.c:517
#5  0x00005555555610ee in main (argc=5, argv=0x7fffffffe4a8)
    at /home/jack/bngblaster/code/bngblaster/src/bbl.c:657
```

qdisc-bypass: false
```
Breakpoint 2, bbl_stream_rx (eth=0x555555b807a0, mac=0x555555b99220 "\016\227\371G\352\b")
    at /home/jack/bngblaster/code/bngblaster/src/bbl_stream.c:2248
2248	    bbl_bbl_s *bbl = eth->bbl;
(gdb) bt
#0  bbl_stream_rx (eth=0x555555b807a0, mac=0x555555b99220 "\016\227\371G\352\b")
    at /home/jack/bngblaster/code/bngblaster/src/bbl_stream.c:2248
#1  0x00005555555bb976 in bbl_rx_stream_a10nsp (interface=0x555555b99200, eth=0x555555b807a0)
    at /home/jack/bngblaster/code/bngblaster/src/bbl_rx.c:55
#2  0x00005555555bbb9b in bbl_rx_handler (interface=0x555555b842d0, eth=0x555555b807a0)
    at /home/jack/bngblaster/code/bngblaster/src/bbl_rx.c:118
#3  0x00005555555e9688 in io_packet_mmap_rx_job (timer=0x555555b834f0)
    at /home/jack/bngblaster/code/bngblaster/src/io/io_packet_mmap.c:100
#4  0x000055555555e017 in timer_walk (root=0x555555b802a0)
    at /home/jack/bngblaster/code/common/src/timer.c:517
#5  0x00005555555610ee in main (argc=5, argv=0x7fffffffe4a8)
    at /home/jack/bngblaster/code/bngblaster/src/bbl.c:657

```
