### ISSUE TITLE
Blaster crash observed after fibd restart at rbfs side

### ISSUE THREAD

**Issue by pratibhatomar9** [rtbrick/bngblaster#257]
**Blaster crash observed when fibd restart performed at RBFS**

**To Reproduce**

Version (`bngblaster -v`):

```
supervisor@SN1-STD-26-3625926:~ $ bngblaster -v
Version: 0.8.51
Compiler: GNU (11.4.0)
IO Modes: packet_mmap_raw (default), packet_mmap, raw
supervisor@SN1-STD-26-3625926:~ $ 

```

JSON configuration:
```
{
    "body": {
        "interfaces": {
            "access": [
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "ipoe",
                    "dhcp": true,
                    "outer-vlan-min": 1001,
                    "outer-vlan-max": 1001,
                    "inner-vlan-min": 1001,
                    "inner-vlan-max": 1001
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "ipoe",
                    "dhcp": true,
                    "outer-vlan-min": 1002,
                    "outer-vlan-max": 1002,
                    "inner-vlan-min": 1002,
                    "inner-vlan-max": 1002
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "ipoe",
                    "dhcp": true,
                    "outer-vlan-min": 1003,
                    "outer-vlan-max": 1003,
                    "inner-vlan-min": 1003,
                    "inner-vlan-max": 1003
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "ipoe",
                    "dhcp": true,
                    "outer-vlan-min": 1004,
                    "outer-vlan-max": 1004,
                    "inner-vlan-min": 1004,
                    "inner-vlan-max": 1004
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "ipoe",
                    "dhcp": true,
                    "outer-vlan-min": 1005,
                    "outer-vlan-max": 1005,
                    "inner-vlan-min": 1005,
                    "inner-vlan-max": 1005
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "pppoe",
                    "username": "user1@t-online.de",
                    "password": "test",
                    "outer-vlan-min": 1,
                    "outer-vlan-max": 1,
                    "inner-vlan-min": 1,
                    "inner-vlan-max": 1,
                    "authentication-protocol": "PAP"
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "pppoe",
                    "username": "user2@t-online.de",
                    "password": "test",
                    "outer-vlan-min": 2,
                    "outer-vlan-max": 2,
                    "inner-vlan-min": 2,
                    "inner-vlan-max": 2,
                    "authentication-protocol": "PAP"
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "pppoe",
                    "username": "user3@t-online.de",
                    "password": "test",
                    "outer-vlan-min": 3,
                    "outer-vlan-max": 3,
                    "inner-vlan-min": 3,
                    "inner-vlan-max": 3,
                    "authentication-protocol": "PAP"
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "pppoe",
                    "username": "user4@t-online.de",
                    "password": "test",
                    "outer-vlan-min": 4,
                    "outer-vlan-max": 4,
                    "inner-vlan-min": 4,
                    "inner-vlan-max": 4,
                    "authentication-protocol": "PAP"
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "pppoe",
                    "username": "user5@t-online.de",
                    "password": "test",
                    "outer-vlan-min": 5,
                    "outer-vlan-max": 5,
                    "inner-vlan-min": 5,
                    "inner-vlan-max": 5,
                    "authentication-protocol": "PAP"
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "pppoe",
                    "username": "l2tp1server@rtbrick.com",
                    "password": "test",
                    "outer-vlan-min": 6,
                    "outer-vlan-max": 6,
                    "inner-vlan-min": 6,
                    "inner-vlan-max": 6,
                    "authentication-protocol": "PAP"
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "pppoe",
                    "username": "l2tp1server@rtbrick.com",
                    "password": "test",
                    "outer-vlan-min": 7,
                    "outer-vlan-max": 7,
                    "inner-vlan-min": 7,
                    "inner-vlan-max": 7,
                    "authentication-protocol": "PAP"
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "pppoe",
                    "username": "l2tp2server@rtbrick.com",
                    "password": "test",
                    "outer-vlan-min": 8,
                    "outer-vlan-max": 8,
                    "inner-vlan-min": 8,
                    "inner-vlan-max": 8,
                    "authentication-protocol": "PAP"
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "pppoe",
                    "username": "l2tp2server@rtbrick.com",
                    "password": "test",
                    "outer-vlan-min": 9,
                    "outer-vlan-max": 9,
                    "inner-vlan-min": 9,
                    "inner-vlan-max": 9,
                    "authentication-protocol": "PAP"
                },
                {
                    "interface": "SN1-2-C1",
                    "network-interface": "SN1-3-C1",
                    "type": "pppoe",
                    "username": "l2tp2server@rtbrick.com",
                    "password": "test",
                    "outer-vlan-min": 10,
                    "outer-vlan-max": 10,
                    "inner-vlan-min": 10,
                    "inner-vlan-max": 10,
                    "authentication-protocol": "PAP"
                }
            ],
            "network": [
                {
                    "interface": "SN1-3-C1",
                    "address": "132.1.1.3",
                    "gateway": "132.1.1.1",
                    "address-ipv6": "2003:156:101:101::2",
                    "gateway-ipv6": "2003:156:101:101::1"
                },
                {
                    "interface": "SN1-6-C2",
                    "address": "23.1.1.3/24",
                    "gateway": "23.1.1.2",
                    "isis-instance-id": 1,
                    "isis-level": 1
                },
                {
                    "interface": "SN1-7-RR",
                    "address": "34.1.1.3/24",
                    "gateway": "34.1.1.4",
                    "isis-instance-id": 1,
                    "isis-level": 1
                }
            ]
        },
        "sessions": {
            "count": 15,
            "max-outstanding": 100,
            "start-rate": 100,
            "stop-rate": 100
        },
        "pppoe": {
            "reconnect": true,
            "discovery-timeout": 5,
            "discovery-retry": 3
        },
        "access-line": {
            "agent-remote-id": "DEU.RTBRICK.{session-global}",
            "agent-circuit-id": "0.0.0.0/0.0.0.0 eth 0:{session-global}",
            "rate-up": 1024,
            "rate-down": 16384
        },
        "ppp": {
            "mru": 1492,
            "authentication": {
                "username": "user{session-global}@t-online.de",
                "password": "test",
                "timeout": 5,
                "retry": 30,
                "protocol": "PAP"
            },
            "lcp": {
                "conf-request-timeout": 5,
                "conf-request-retry": 10,
                "keepalive-interval": 30,
                "keepalive-retry": 3
            },
            "ipcp": {
                "enable": true,
                "conf-request-timeout": 5,
                "conf-request-retry": 10
            },
            "ip6cp": {
                "enable": true,
                "conf-request-timeout": 5,
                "conf-request-retry": 10
            }
        },
        "dhcp": {
            "enable": true
        },
        "dhcpv6": {
            "enable": true,
            "rapid-commit": true
        },
        "igmp": {
            "autostart": true,
            "version": 3,
            "start-delay": 5,
            "group": "232.1.1.1",
            "group-iter": "0.0.0.1",
            "source": "132.1.1.3",
            "group-count": 1,
            "send-multicast-traffic": false
        },
        "session-traffic": {
            "ipv4-pps": 10,
            "ipv6-pps": 10,
            "ipv6pd-pps": 10,
            "autostart": false
        },
        "l2tp-server": [
            {
                "name": "LNS1",
                "address": "134.1.1.11",
                "secret": "rtbrick",
                "receive-window-size": 8,
                "data-control-priority": "false",
                "data-length": "false",
                "data-offset": "false"
            },
            {
                "name": "LNS2",
                "address": "134.1.1.12",
                "secret": "rtbrick",
                "receive-window-size": 8,
                "data-control-priority": "false",
                "data-length": "false",
                "data-offset": "false"
            }
        ],
        "isis": [
            {
                "instance-id": 1,
                "area": [
                    "49.0001/24"
                ],
                "system-id": "1921.6100.1003",
                "router-id": "172.168.1.3",
                "hostname": "sn1",
                "hello-padding": true,
                "sr-base": 300000,
                "sr-range": 2000,
                "sr-node-sid": 300,
                "teardown-time": 15,
                "lsp-tx-interval": 5,
                "lsp-tx-window-size": 5
            }
        ],
        "bgp": [
            {
                "__comment__": "RR-IPv4",
                "network-interface": "SN1-7-RR",
                "local-ipv4-address": "172.168.1.3",
                "peer-ipv4-address": "172.168.1.4",
                "raw-update-file": "/home/supervisor/ipv4_nlri.bgp",
                "local-as": 65001,
                "peer-as": 65001
            },
            {
                "__comment__": "RR-IPv6",
                "network-interface": "SN1-7-RR",
                "local-ipv4-address": "172.168.1.3",
                "peer-ipv4-address": "173.168.1.4",
                "raw-update-file": "/home/supervisor/ipv6_nlri.bgp",
                "local-as": 65001,
                "peer-as": 65001
            }
        ]
    },
    "data": null,
    "headers": {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "User-Agent": "RESTApi"
    },
    "timeout": [
        5,
        60
    ],
    "timestamp": "2024-05-10T04:29:07.512015+00:00"
}
```

1. Fibd restart at RBFS

**Additional context**

BT >
-----
Program received signal SIGSEGV, Segmentation fault.
0x00007ff15cea875b in kill () at ../sysdeps/unix/syscall-template.S:120
120    ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007ff15cea875b in kill () at ../sysdeps/unix/syscall-template.S:120
#1  0x0000560e7dc72b56 in ?? ()
#2  0x00007ff15ce8fd90 in __libc_start_call_main (main=main@entry=0x560e7dc6fec0, argc=argc@entry=5, argv=argv@entry=0x7ffc71faab08) at ../sysdeps/nptl/libc_start_call_main.h:58
#3  0x00007ff15ce8fe40 in __libc_start_main_impl (main=0x560e7dc6fec0, argc=5, argv=0x7ffc71faab08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc71faaaf8)
    at ../csu/libc-start.c:392
#4  0x0000560e7dc72bb5 in ?? ()
(gdb)

**Comment by GIC-de** [comment]
This issue might be already fix but is moved to internal bugzilla tracker for tracking.
